VCS_OPTS   = -full64 -sverilog
VCS_OPTS  += -ntb_opts uvm-1.2
VCS_OPTS  += -tiemscale=1ns/1ps
VCS_OPTS  += -debug_access+all -kdb -lca
VCS_OPTS  += -cm line+cond+fsm+tgl+branch+assert
VCS_OUTPUT = -o simv
VCS_INCDIR = +incdir+../tb +incdir+../rtl
VCS_SRC_FILES = ../rtl/ram.sv ../tb/ram_if.sv ../tb/ram_pkg.sv ../tb/tb_top.sv

TEST ?= ram_basic_test
SEED ?= 1
INFO_LEVEL ?= UVM_MEDIUM

SIMV_OPTS  = +UVM_TESTNAME=$(TEST)
SIMV_OPTS += +UVM_VERBOSITY=$(INFO_LEVEL)
SIMV_OPTS += +ntb_randome_seed = $(SEED)
SIMV_OPTS += -cm line+cond+fsm+tgl+branch+assert
SIMV_OPTS += -cm_dir coverage.vdb
SIMV_OPTS += -cm_name sim1

.PHONY: all comp simv clean

all: simv

comp:
	@vcs $(VCS_OPTS) $(VCS_OUTPUT) $(VCS_INCDIR) $(VCS_SRC_FILES)
	@echo "target [$@]"

simv: comp
	@./simv $(SIMV_OPTS)
	@echo "dependancy target [$<]"
	@echo "target [$@]"


clean:
	@rm -rf simv* csrc *.log *.key *.h
	@echo "clean directory"


A := hello
B := $(A) world
A ?= goodbye

test:
	@echo $(B)
